### ISSUE TITLE
feat: hubs should track fnames

### ISSUE THREAD

**Issue by varunsrin** [farcasterxyz/hub#128] opened 2022-09-26 20:08 UTC
**What is the feature you would like to implement?**
Hubs should keep track of the current fname for a user as well as expose it in all relevant APIs

**Why is this feature important?**
Keeping tracking of valid fnames is something every app cares about and doing it at the hub level ensures consistency.

**Will the protocol spec need to be updated??**
No

**How should this feature be built? (optional)**

### Suggested spec

* Watch NameRegistry for `Transfer` events and merge transfer event into engine when we see them.
* Store list of transfer events by fname (`fname!<fname> => <name registry entry>`) to look up the most recent custody address and expiry per fname (see `NameRegistryEntry` type below)
* Calculate the expiry by adding 1 year to the timestamp of the block number OR calling `expiryOf` attribute on NameRegistry contract, because the `Transfer` event doesn't have expiry
* Watch NameRegistry for `Renew` events and update fname entry when expiry changes
* Index names by expiry (`fnameExpiry!<expiry> => <fname>`) and write a service that scans the fname expiry list and tries to expire fnames. 

Expiring an fname includes:
  1. Confirming with the NameRegistry that the name should be expired
  2. Deleting the `fname!<fname>` entry
  3. Deleting the `ProfileNameAdd` message that points to that name (if applicable)

### NameRegistryEntry type
```
type NameRegistryEntry = {
  transfer: <transfer event>; // how can we integrate this with the IDRegistryEvent type we already have?
  expiry: number; // expiration timestamp, updated on renew
}
```

**Additional context**

Need to think through the following cases: 

- Users who transfer an fid to a new address should be able to login with that address/seed
- Users who transfer an fname out of their fid should should be handled correctly
- Users who transfer an fname into their fid should be handled correctly
- Users with multiple fnames
- Users whose names expire
- Users who renew their names before they expire
- Users who bid on and win an expired name
- Users who perform a recovery on their name

**Comment by pfletcherhill** [comment] 2022-09-27 19:52
Some replies/notes after reading this:
* Are we sure we want to treat fnames differently than ENS names? We had previously said we want to make it easy for a user to opt out of the Farcaster Name ecosystem and use ENS or another name system instead. Having hubs handle fnames natively may not be consistent with that.
* The hubs watch `Register` and `Transfer` events on the ID Registry, so as soon as those events hit and are confirmed, the new address should be able to authenticate as the custody address for an fid via hubs.
* Is there a way to make use of verifications when assigning an fname to an fid? To that end, how are we thinking about invalidating NFT verifications when the NFT in question is transferred?
* I think declaring an fname for use by an fid should be a message and maybe part of a profile metadata message.

**Comment by varunsrin** [comment] 2022-10-03 18:40
Discussed offline about tracking other assets. The general takeaway is: 

1. Hubs should allow for metadata (#120) that lets users make declarations about on-chain ownerships like nfts, fnames, ens etc and set preferences about which ones should be displayed. 

2. By default, Hubs shouldn't do the heavy lifting to stay in sync about whether the user still owns a particular asset - that would be very expensive from a networking perspective.  Applications can do this quite easily by getting the metadata from the hubs and then validating ownership against an eth node. 

3. Hubs should do the heavy lifting for fnames -- given that most third party applications want fname support, not doing this introduces a lot of overhead for them. If another asset or namespace becomes heavily used and requested by applications (e.g. ENS) we should consider adding them as well.

**Comment by varunsrin** [comment] 2022-10-03 18:46
@pfletcherhill it looks like your proposal doesn't store the Renew events. Does it make sense to hold onto them given that they are an important state change? Possible that we will want to look up or query them later outside the context of transfer events.

**Comment by pfletcherhill** [comment] 2022-12-02 21:40
## Updated spec

### Problem
We want to be able to identify users by their fid or an fname. However, at the moment, a custody address can own many fnames and users don't have a way to indicate which fname they want to use.

### Overview
* Add `UserNameAdd` message type that allows a user to broadcast to the network that they can be referred to by a given fname
* Keep hub in sync with the Name Registry by maintaining a mapping of fnames to custody addresses in order to validate new `UserNameAdd` messages and revoke `UserNameAdd` messages when the fname changes ownership or expires

### NameRegistry events
Two types of Name Registry events should be tracked:
* `Transfer` - change custody address associated with fname
* `Renew` - change expiration time for fname

These events should be submitted to the `UserDataStore` for merging and persistence. The store should merge events that occur later than the existing event, based on block number and log index. See the `mergeIdRegistryEvent` method in the `SignerStore` class for an example.

NameRegistry events should be represented by a new `NameRegistryEvent` flatbuffer. We had initially intended the `ContractEvent` flatbuffer to represent both IdRegistry and NameRegistry events, but the behavior is different enough to warrant a new flatbuffer (e.g. the IdRegistry events are indexed by fid and the NameRegistry events will be indexed by fname). As a bonus, we should refactor the `ContractEvent` flatbuffer to exclusively be IdRegistry events.

A new `NameRegistryEventModel` class should be created to wrap the `NameRegistryEvent` flatbuffer and define keys for persisting the event to RocksDB. The primary key should be structured as `<RootPrefix.NameRegistryEvent, fname>` (see the `primaryKey` method in the `ContractEventModel` class for reference.

### UserNameAdd messages
The UserDataStore will also handle merging new `UserNameAdd` messages which will require updating the flatbuffer Message schema. Here's a draft schema for the body:
```
table UserNameAddBody {
  fname: [ubyte]
}

```

Users should be able to remove any fname from their fid by sending a `UserNameAdd` message with a blank `fname` field.

Conflicts between `UserNameAdd` messages (i.e. messages with the same fid) should be resolved using LWW mechanics, like `UserDataAdd` messages.

A `UserNameAdd` message is valid if the current owner of the fname is the custody address, based on the NameRegistry events that have been merged.

### Transferring fnames
When fnames are transferred, if a `UserNameAdd` message exists for that fname, the message should be revoked, because if that message were to be merged after the transfer it would be rejected. `UserNameAdd` messages should be revoked the same way `SignerAdd` messages are revoked when an fid is transferred between custody addresses.

### Expiring fnames
When an fname expires, the relevant `UserNameAdd` message should be revoked as if the fname had been transferred. However, expiration of an fname does not emit a contract event, so we will have to keep track of fname expirations separately. We can do this by indexing `NameRegistryEvent` objects by their expiration time and running a regular job to expire the oldest events. See the way messages are indexed by signer in MessageModel for an example of how to index events. The key for the index should look like: `<RootPrefix.NameRegistryEventExpiration, expiration time>` and include the fname as the value.

**Closed** 2022-12-30 18:44 UTC
Labels: feat
